#!/usr/bin/env python3
"""Property tests for the one authoritative per-action size-budget table.

The R1/F4/F5 size-contract class: schema maxima, canonical byte caps, repair
candidate retention, prompt budgets, and result-artifact reads were each
locally reasonable and jointly inconsistent, so a schema-valid maximal result
could be rejected by its own byte bound, an oversized delivered candidate was
dropped before the correction turn could see it, and the NL repair prompt
truncated candidates the NL schema itself permits. These tests keep every
relationship in `agent_runtime/size_budget.py` true:

- For every action, a generated byte-maximal schema-valid candidate fits the
  action's final-byte cap with explicit headroom.
- An oversized delivered candidate is retained in bounded truncated form and
  stays correction-eligible.
- Every potentially valid nl-decision-v1 candidate reaches the repair turn
  complete, in both the direct-stdin and env-carried repair lanes.
- Consumers read the caps from the one table instead of copied constants.
"""

from __future__ import annotations

import json
import tempfile
from pathlib import Path
import sys

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))
sys.path.append(str(ROOT / "scripts"))
sys.path.append(str(ROOT / "tests"))

from agent_runtime import size_budget  # noqa: E402
from agent_runtime.contract import (  # noqa: E402
    canonical_json_bytes,
    validate_schema,
)
from agent_runtime.size_budget import (  # noqa: E402
    COMPILED_PROMPT_MAX_BYTES,
    ENV_PROMPT_MAX_BYTES,
    FINAL_HEADROOM_BYTES,
    GITHUB_COMMENT_MAX_CHARS,
    MAX_ARG_STRLEN,
    MAX_FINAL_BYTES_CEILING,
    NL_ANSWER_MAX_CHARS,
    NL_FREE_TEXT_MAX_CHARS,
    NL_REPAIR_CANDIDATE_MAX_BYTES,
    RESULT_ARTIFACT_MAX_BYTES,
    SIZE_BUDGETS,
    SizeBudgetError,
    TRIAGE_REPAIR_CANDIDATE_MAX_BYTES,
    bounded_candidate_text,
    bounded_github_comment,
    claude_action_packed_prompt_bytes,
    delivered_retention_canonical_max_bytes,
    schema_worst_case_canonical_bytes,
)

FAILURES = []


def check(label, ok):
    print(("ok   " if ok else "FAIL ") + label)
    if not ok:
        FAILURES.append(label)


def read(*parts):
    return (ROOT.joinpath(*parts)).read_text(encoding="utf-8")


# --------------------------------------------------------------------------- #
# Byte-maximal schema-valid candidate generator
# --------------------------------------------------------------------------- #

# Worst-case fill: a control character costs six canonical bytes per schema
# character, the walker's own accounting.
_FILL = "\x00"


def _pattern_value(pattern, salt):
    if pattern.startswith("^sha256:"):
        return "sha256:" + format(salt, "x").rjust(64, "0")
    if "[0-9a-f]" in pattern:
        return format(salt, "x").rjust(64, "0")
    if pattern.startswith("^[a-z0-9]"):
        return ("a" + format(salt, "x")).ljust(64, "b")[:64]
    if "target-src/" in pattern:
        suffix = str(salt)
        return "target-src/" + ("p" * (900 - len(suffix))) + suffix
    raise AssertionError("unhandled pattern %r" % pattern)


def maximal_candidate(schema, defs=None, salt=0):
    """One byte-maximal schema-valid candidate mirroring the walker's choices."""
    if defs is None:
        defs = schema.get("$defs", {}) or {}
    if "$ref" in schema:
        return maximal_candidate(defs[schema["$ref"].split("/")[-1]], defs, salt)
    if "oneOf" in schema:
        return max(
            (maximal_candidate(branch, defs, salt) for branch in schema["oneOf"]),
            key=lambda value: len(canonical_json_bytes(value)),
        )
    if "const" in schema:
        return schema["const"]
    if "enum" in schema:
        return max(schema["enum"], key=lambda value: len(canonical_json_bytes(value)))
    node_type = schema.get("type")
    if node_type == "string":
        pattern = schema.get("pattern")
        if pattern is not None:
            return _pattern_value(pattern, salt)
        return _FILL * schema["maxLength"]
    if node_type == "integer":
        return max(
            (schema["minimum"], schema["maximum"]),
            key=lambda value: len(canonical_json_bytes(value)),
        )
    if node_type == "boolean":
        return True
    if node_type == "array":
        return [
            maximal_candidate(schema["items"], defs, index)
            for index in range(schema["maxItems"])
        ]
    if node_type == "object":
        return {
            key: maximal_candidate(sub, defs, salt)
            for key, sub in schema.get("properties", {}).items()
        }
    raise AssertionError("unsupported schema node %r" % schema)


def action_schema(action):
    path = ROOT / "agent_runtime" / "schemas" / "actions" / SIZE_BUDGETS[action].schema_file
    return json.loads(path.read_text(encoding="utf-8"))


def main():
    try:
        schema_worst_case_canonical_bytes({"type": "integer", "minimum": 1})
        rejected_unbounded_integer = False
    except SizeBudgetError:
        rejected_unbounded_integer = True
    check(
        "walker: an integer without both finite bounds is rejected",
        rejected_unbounded_integer,
    )

    # ------------------------------------------------------------------ #
    # A. Per-action property: byte-maximal schema-valid candidate fits the
    #    final-byte cap with explicit headroom.
    # ------------------------------------------------------------------ #
    for action, budget in sorted(SIZE_BUDGETS.items()):
        schema = action_schema(action)
        worst = schema_worst_case_canonical_bytes(schema)
        candidate = maximal_candidate(schema)
        try:
            validate_schema(candidate, schema)
            valid = True
        except Exception:  # noqa: BLE001 - any rejection fails the property
            valid = False
        size = len(canonical_json_bytes(candidate))
        check(
            "budget[%s]: byte-maximal candidate is schema-valid" % action, valid
        )
        check(
            "budget[%s]: walker bound dominates the generated maximum (%d >= %d)"
            % (action, worst, size),
            worst >= size,
        )
        check(
            "budget[%s]: maximal candidate fits the cap with headroom (%d + %d <= %d)"
            % (action, size, FINAL_HEADROOM_BYTES, budget.max_final_bytes),
            size + FINAL_HEADROOM_BYTES <= budget.max_final_bytes,
        )
        check(
            "budget[%s]: walker bound fits the cap with headroom (%d + %d <= %d)"
            % (action, worst, FINAL_HEADROOM_BYTES, budget.max_final_bytes),
            worst + FINAL_HEADROOM_BYTES <= budget.max_final_bytes,
        )
        check(
            "budget[%s]: cap is a reviewable 4096 multiple under the ceiling"
            % action,
            budget.max_final_bytes % 4096 == 0
            and budget.max_final_bytes <= MAX_FINAL_BYTES_CEILING,
        )
        check(
            "budget[%s]: bounded retention stays far under the result read cap"
            % action,
            delivered_retention_canonical_max_bytes(action)
            <= RESULT_ARTIFACT_MAX_BYTES // 4,
        )

    # ------------------------------------------------------------------ #
    # B. One owner: consumers use the table, not copied constants.
    # ------------------------------------------------------------------ #
    from agent_runtime.task_builder import (
        ACTION_LIMITS,
        CORRECTION_CANDIDATE_MAX_BYTES,
    )

    check(
        "owner: ACTION_LIMITS covers exactly the budgeted actions",
        set(ACTION_LIMITS) == set(SIZE_BUDGETS),
    )
    check(
        "owner: every ACTION_LIMITS final-byte column comes from the table",
        all(
            ACTION_LIMITS[action][4] == SIZE_BUDGETS[action].max_final_bytes
            for action in ACTION_LIMITS
        ),
    )
    check(
        "owner: the triage correction embed bound is the table's",
        CORRECTION_CANDIDATE_MAX_BYTES == TRIAGE_REPAIR_CANDIDATE_MAX_BYTES,
    )
    import render_card as rc

    check(
        "owner: render_card repair candidate bound is the table's",
        rc.REPAIR_CANDIDATE_MAX_BYTES == TRIAGE_REPAIR_CANDIDATE_MAX_BYTES,
    )
    import apply_decision as ad

    check(
        "owner: apply_decision NL repair candidate bound is the table's",
        ad.NL_REPAIR_CANDIDATE_MAX_BYTES == NL_REPAIR_CANDIDATE_MAX_BYTES,
    )
    task_schema = json.loads(
        read("agent_runtime", "schemas", "v1alpha1", "agent-task.schema.json")
    )
    check(
        "owner: the AgentTask maxFinalBytes ceiling equals the table ceiling",
        task_schema["properties"]["spec"]["properties"]["limits"]["properties"][
            "maxFinalBytes"
        ]["maximum"]
        == MAX_FINAL_BYTES_CEILING,
    )
    result_schema = json.loads(
        read("agent_runtime", "schemas", "v1alpha1", "agent-result.schema.json")
    )
    check(
        "owner: AgentResult delivered/final byte ceilings equal the table ceiling",
        result_schema["properties"]["delivered"]["properties"]["bytes"]["maximum"]
        == MAX_FINAL_BYTES_CEILING
        and result_schema["properties"]["final"]["properties"]["bytes"]["maximum"]
        == MAX_FINAL_BYTES_CEILING,
    )
    consumer_src = read("agent_runtime", "consumer.py")
    check(
        "owner: consumer result reads use RESULT_ARTIFACT_MAX_BYTES",
        "max_bytes=RESULT_ARTIFACT_MAX_BYTES" in consumer_src
        and "2 * 1024 * 1024" not in consumer_src,
    )
    worker_src = read("agent_runtime", "worker.py")
    check(
        "owner: worker prompt admission uses COMPILED_PROMPT_MAX_BYTES",
        "COMPILED_PROMPT_MAX_BYTES" in worker_src
        and "262144" not in worker_src,
    )
    builder_src = read("agent_runtime", "task_builder.py")
    check(
        "owner: task builder selects the adapter-specific prompt transport cap",
        builder_src.count('adapter == "claude-action-compat"') >= 2
        and builder_src.count("ENV_PROMPT_MAX_BYTES") >= 3
        and builder_src.count("COMPILED_PROMPT_MAX_BYTES") >= 3
        and builder_src.count("claude_action_packed_prompt_bytes(compiled_prompt)") == 2
        and "bundle, 262144" not in builder_src,
    )
    decision_yaml = read(".github", "workflows", "decision-handler.yml")
    check(
        "owner: trusted NL prompts reach task construction by file, not step env",
        "NL_PROMPT_FILE: nl-prompt.txt" in decision_yaml
        and "NL_PROMPT: ${{ steps.nl-prompt.outputs.prompt }}" not in decision_yaml
        and "--prompt nl-prompt.txt" in decision_yaml,
    )
    check(
        "owner: result artifact cap covers delivered plus final at the largest cap",
        RESULT_ARTIFACT_MAX_BYTES
        >= 2 * max(budget.max_final_bytes for budget in SIZE_BUDGETS.values())
        + 65536,
    )
    check(
        "owner: correction-path result reads dominate the result artifact cap",
        "max_bytes=16 * 1024 * 1024" in builder_src
        and 16 * 1024 * 1024 >= RESULT_ARTIFACT_MAX_BYTES,
    )

    # ------------------------------------------------------------------ #
    # C. Schema files match the recorded character contract.
    # ------------------------------------------------------------------ #
    nl_schema = action_schema("nl-decision.local")
    check(
        "schema: nl-decision-v1 fields match the budget character contract",
        nl_schema["properties"]["answer"]["maxLength"] == NL_ANSWER_MAX_CHARS
        and nl_schema["properties"]["free_text"]["maxLength"]
        == NL_FREE_TEXT_MAX_CHARS
        and nl_schema["properties"]["action"]["maxLength"]
        == size_budget.NL_ACTION_MAX_CHARS,
    )
    deep_schema = action_schema("deep-review.local")
    check(
        "schema: deep-review text cap equals the GitHub comment consumer bound",
        deep_schema["properties"]["text"]["maxLength"]
        == size_budget.DEEP_REVIEW_TEXT_MAX_CHARS
        == GITHUB_COMMENT_MAX_CHARS,
    )
    check(
        "schema: an NL answer or decline note always fits one argv/env string",
        6 * NL_ANSWER_MAX_CHARS + 4096 <= MAX_ARG_STRLEN
        and 6 * NL_FREE_TEXT_MAX_CHARS + 4096 <= MAX_ARG_STRLEN,
    )
    deep_review_yaml = read(".github", "workflows", "deep-review.yml")
    check(
        "consumer: the bounded final deep-review body travels over stdin",
        '"--input", "-"' in deep_review_yaml
        and '"-f", "body=%s" % body' not in deep_review_yaml,
    )
    check(
        "consumer: deep-review bounds the transformed body after qualification",
        "bounded_github_comment(verdict, os.environ[\"CLAIM_MARKER\"])" in deep_review_yaml,
    )
    maximal_comment = bounded_github_comment(
        "v" * GITHUB_COMMENT_MAX_CHARS,
        "<!-- wheelhouse-agent-event:v1:claim -->",
    )
    check(
        "consumer: final deep-review rendering includes metadata within GitHub's cap",
        len(maximal_comment) <= GITHUB_COMMENT_MAX_CHARS
        and maximal_comment.endswith("<!-- wheelhouse-agent-event:v1:claim -->")
        and "[truncated to fit GitHub comment limit]" in maximal_comment,
    )
    claude_model_yaml = read(".github", "workflows", "claude-model.yml")
    check(
        "consumer: direct results use the authoritative artifact read cap",
        "RESULT_ARTIFACT_MAX_BYTES" in claude_model_yaml
        and 'result.json")" -le 2097152' not in claude_model_yaml,
    )
    check(
        "consumer: production transcript reads use the authoritative cap",
        claude_model_yaml.count("TRANSCRIPT_MAX_BYTES") >= 3
        and "8388608" not in claude_model_yaml,
    )

    # ------------------------------------------------------------------ #
    # D. NL repair capacity: every potentially valid candidate reaches the
    #    repair turn COMPLETE, in both repair lanes.
    # ------------------------------------------------------------------ #
    import apply_decision as decision

    nl_worst = schema_worst_case_canonical_bytes(nl_schema)
    check(
        "nl-repair: the candidate bound covers the schema worst case (%d >= %d)"
        % (NL_REPAIR_CANDIDATE_MAX_BYTES, nl_worst),
        NL_REPAIR_CANDIDATE_MAX_BYTES >= nl_worst,
    )
    repair_overhead = len(decision.build_nl_repair_prompt("").encode("utf-8"))
    check(
        "nl-repair: retained ASCII candidate fits the env-carried rollback lane",
        claude_action_packed_prompt_bytes(
            decision.build_nl_repair_prompt("x" * NL_REPAIR_CANDIDATE_MAX_BYTES)
        )
        <= ENV_PROMPT_MAX_BYTES,
    )
    check(
        "nl-repair: worst-case repair prompt fits the compiled stdin lane",
        repair_overhead + NL_REPAIR_CANDIDATE_MAX_BYTES <= COMPILED_PROMPT_MAX_BYTES,
    )
    # The concrete acceptance shape: a 49 KB schema-invalid candidate reaches
    # the repair model intact, with no truncation marker.
    big_invalid = json.dumps(
        {"mode": "answer", "answer": "a" * 48000, "bogus": 1}
    )
    check(
        "nl-repair: fixture candidate is the intended shape (49 KB, schema-invalid)",
        len(big_invalid.encode("utf-8")) >= 48000
        and decision.nl_schema_reason(big_invalid) != "",
    )
    prompt = decision.build_nl_repair_prompt(big_invalid)
    check(
        "nl-repair: the 49 KB candidate reaches the repair prompt complete",
        big_invalid in prompt and "[candidate truncated" not in prompt,
    )
    # The actual six-byte-per-character maximum must survive both transport
    # lanes. Its canonical \u00XX escapes grow again when the whole prompt is
    # JSON-packed for the action lane, so the prompt uses the reversible
    # compact transport notation rather than rejecting or truncating it.
    worst_valid = {
        "mode": "clarify",
        "action": "\x00" * size_budget.NL_ACTION_MAX_CHARS,
        "free_text": "\x00" * NL_FREE_TEXT_MAX_CHARS,
        "answer": "\x00" * NL_ANSWER_MAX_CHARS,
    }
    validate_schema(worst_valid, nl_schema)
    worst_valid_text = canonical_json_bytes(worst_valid).decode("utf-8")
    worst_prompt = decision.build_nl_repair_prompt(worst_valid_text)
    check(
        "nl-repair: the six-byte schema maximum is complete and never truncated",
        "TRANSPORT NOTE:" in worst_prompt
        and '"answer":"~00~00~00' in worst_prompt
        and worst_prompt.count("~00")
        == (
            size_budget.NL_ACTION_MAX_CHARS
            + NL_FREE_TEXT_MAX_CHARS
            + NL_ANSWER_MAX_CHARS
        )
        and "[candidate truncated" not in worst_prompt,
    )
    check(
        "nl-repair: the worst schema-valid prompt fits after action JSON packing",
        claude_action_packed_prompt_bytes(worst_prompt) <= ENV_PROMPT_MAX_BYTES,
    )
    transport_source = "~literal~" + "".join(
        chr(codepoint) for codepoint in range(0x20)
    ) + "\x7f"
    transported = json.loads(
        decision._compact_valid_nl_candidate(
            {"mode": "answer", "answer": transport_source}
        )
    )["answer"]
    decoded = []
    index = 0
    while index < len(transported):
        if transported[index : index + 2] == "~~":
            decoded.append("~")
            index += 2
        elif transported[index] == "~":
            decoded.append(chr(int(transported[index + 1 : index + 3], 16)))
            index += 3
        else:
            decoded.append(transported[index])
            index += 1
    check(
        "nl-repair: compact worst-case transport is reversible without collisions",
        "".join(decoded) == transport_source,
    )
    # Junk beyond the bound is truncated with an explicit marker, not dropped.
    junk = "x" * (NL_REPAIR_CANDIDATE_MAX_BYTES + 50000)
    junk_prompt = decision.build_nl_repair_prompt(junk)
    check(
        "nl-repair: junk beyond the bound is marker-truncated, never silent",
        "[candidate truncated: retained" in junk_prompt
        and len(junk_prompt.encode("utf-8"))
        <= repair_overhead + NL_REPAIR_CANDIDATE_MAX_BYTES + 128,
    )
    escape_heavy = "\\" * 80000
    escape_prompt = decision.build_nl_repair_prompt(escape_heavy)
    check(
        "nl-repair: escape-heavy invalid input truncates to the final packed bound",
        "[candidate truncated: retained" in escape_prompt
        and claude_action_packed_prompt_bytes(escape_prompt)
        <= ENV_PROMPT_MAX_BYTES,
    )

    # ------------------------------------------------------------------ #
    # E. An oversized delivered candidate is retained bounded and stays
    #    correction-eligible (the F4 lost-candidate class).
    # ------------------------------------------------------------------ #
    from test_triage_schema_repair import _correction_fixture
    from agent_runtime.task_builder import correction_eligibility

    oversized = {
        "summary": "S" * 2_000_000,
        "product_implications": "p",
        "recommended_action": "hold",
        "recommended_reason": "r",
        "evidence": "add bounded stop conditions",
        "recommendation_basis": {
            "kind": "other",
            "observation_id": "sha256:" + "0" * 64,
            "context_id": "sha256:" + "0" * 64,
        },
    }
    with tempfile.TemporaryDirectory() as d:
        task, handoff, handoff_sha, result_dir, result, source_sha = (
            _correction_fixture(d, oversized)
        )
        delivered = result.get("delivered") or {}
        value = delivered.get("value")
        cap = SIZE_BUDGETS["triage.pr.search"].max_final_bytes
        check(
            "oversize: the bridge fails the candidate without losing it",
            result["status"] == "failed"
            and result["error"]["code"] == "output.schema_invalid"
            and isinstance(value, str),
        )
        check(
            "oversize: retention is bounded with an explicit marker",
            "[candidate truncated: retained" in (value or "")
            and delivered.get("bytes", 0)
            <= delivered_retention_canonical_max_bytes("triage.pr.search")
            and len((value or "").encode("utf-8"))
            <= TRIAGE_REPAIR_CANDIDATE_MAX_BYTES + 128,
        )
        check(
            "oversize: the original candidate genuinely exceeded the cap",
            len(canonical_json_bytes(oversized)) > cap,
        )
        ok, reason, errors = correction_eligibility(
            str(handoff), str(result_dir), "abcdef1", source_sha, handoff_sha
        )
        check(
            "oversize: the retained candidate stays correction-eligible",
            ok and reason == "" and len(errors) >= 1,
        )

    # ------------------------------------------------------------------ #
    # F. Bridge retention for an oversized NL candidate feeds the repair
    #    planner in bounded form (never a silent no-candidate).
    # ------------------------------------------------------------------ #
    from test_agent_runtime_claude_bridge import make_bundle, run_bridge, transcript

    with tempfile.TemporaryDirectory() as directory:
        root = Path(directory)
        _, bundle = make_bundle(root / "nl-oversize", action="nl-decision.local")
        huge_nl = json.dumps({"mode": "answer", "answer": "a" * 200000})
        execution = root / "nl-oversize-exec.json"
        transcript(execution, "claude-sonnet-4-6", huge_nl)
        result, _ = run_bridge(bundle, execution, "nl-oversize")
        value = (result.get("delivered") or {}).get("value")
        check(
            "nl-oversize: bridge retains a bounded marker-truncated candidate",
            result["status"] == "failed"
            and isinstance(value, str)
            and "[candidate truncated: retained" in value
            and len(value.encode("utf-8"))
            <= NL_REPAIR_CANDIDATE_MAX_BYTES + 128,
        )
        plan = decision.plan_nl_repair(value)
        check(
            "nl-oversize: the retained candidate reaches the repair planner",
            plan["repair_needed"] is True and value[:1000] in plan["prompt"],
        )

    # ------------------------------------------------------------------ #
    # G. Bounded-candidate helper properties.
    # ------------------------------------------------------------------ #
    intact = bounded_candidate_text("short", 100)
    truncated = bounded_candidate_text("y" * 300, 100)
    check(
        "helper: bounded_candidate_text keeps small text and marks truncation",
        intact == "short"
        and truncated.startswith("y" * 100)
        and "[candidate truncated: retained 100 of 300 bytes]" in truncated,
    )
    check(
        "helper: the truncation marker stays within its accounted bound",
        len(
            (
                size_budget.CANDIDATE_TRUNCATION_TEMPLATE
                % (10**9, 10**10)
            ).encode("utf-8")
        )
        <= size_budget.CANDIDATE_TRUNCATION_MARKER_MAX_BYTES,
    )

    print()
    if FAILURES:
        print("%d size-budget checks failed:" % len(FAILURES))
        for failure in FAILURES:
            print("- %s" % failure)
        raise SystemExit(1)
    print("all size-budget checks passed")


if __name__ == "__main__":
    main()
